@K:\pm\11aug\permission1.SQL;
@K:\pm\11aug\user_creation.SQL;

@K:\pm\11aug\pg_formatting.SQL;

@K:\pm\11aug\install.SQL;
@K:\pm\11aug\lib_mgmt.pkh;
@K:\pm\11aug\lib_mgmt.pkb;
@K:\pm\11aug\run_book_issue_return.SQL;
@K:\pm\11aug\run_enter_and_maintain_books.SQL;
@K:\pm\11aug\run_enter_and_maintain_members.SQL;
@K:\pm\11aug\run_enter_and_maintain_address.SQL;
@K:\pm\11aug\run_get_fine.SQL;
@K:\pm\11aug\book_status_report.SQL
@K:\pm\11aug\daily_student_dues_report.SQL
@K:\pm\11aug\reports.SQL
@K:\pm\11aug\home_page.SQL;
@K:\pm\11aug\contact_us.SQL;
@K:\pm\11aug\about_us.SQL;

